export const ASSAM_CONSTITUENCIES = [
    "Gossaigaon", "Dotama (ST)", "Kokrajhar (ST)", "Baokhungri", "Parbatjhora",
    "Golakganj", "Gauripur", "Dhubri", "Birsing Jarua", "Bilasipara",
    "Mankachar", "Jaleshwar", "Goalpara West (ST)", "Goalpara East", "Dudhnai (ST)",
    "Abhayapuri", "Srijangram", "Bongaigaon", "Sidli Chirang (ST)", "Bijni",
    "Bhowanipur-Sorbhog", "Mandia", "Chenga", "Barpeta (SC)", "Pakabetbari",
    "Bajali", "Chamaria", "Boko-Chaygaon (ST)", "Palasbari", "Hajo-Sualkuchi (SC)",
    "Rangia", "Kamalpur", "Dispur", "Dimoria (SC)", "New Guwahati",
    "Guwahati Central", "Jalukbari", "Barkhetri", "Nalbari", "Tihu",
    "Manas", "Baksa (ST)", "Tamulpur (ST)", "Goreswar", "Bhergaon",
    "Udalguri (ST)", "Majbat (ST)", "Tangla", "Sipajhar", "Mangaldai",
    "Dalgaon", "Nagaon-Batadraba", "Dhing", "Rupohihat", "Samaguri",
    "Jagiroad (SC)", "Marigaon", "Laharighat", "Raha (SC)", "Lumding",
    "Hojai", "Kaliabor", "Barhampur", "Binnakandi", "Golaghat",
    "Dergaon (SC)", "Bokakhat", "Khumtai", "Sarupathar", "Majuli (ST)",
    "Titabor", "Mariani", "Jorhat", "Teok", "Amguri",
    "Nazira", "Sibsagar", "Mahmora", "Sonari", "Demow",
    "Thowra", "Dhakuakhana (ST)", "Dhemaji (ST)", "Sissiborgaon", "Jonai (ST)",
    "Chabua-Lahowal", "Khowang", "Dibrugarh", "Duliajan", "Tingkhong",
    "Naharkatia", "Doomdooma", "Margherita", "Digboi", "Makum",
    "Tinsukia", "Sadiya", "Lakhipur", "Udharbond", "Katigorah",
    "Barkhola", "Silchar", "Sonai", "Dholai (SC)", "Hailakandi",
    "Algapur-Katlicherra", "Karimganj North", "Karimganj South", "Patharkandi", "Ram Krishana Nagar (SC)",
    "Bokajan (ST)", "Howraghat (ST)", "Diphu (ST)", "Rongkhang (ST)", "Amri (ST)",
    "Haflong (ST)", "Biswanath", "Behali", "Gohpur", "Bihpuria",
    "Naduar", "Dhekiajuli", "Barchalla", "Tezpur", "Rangapara",
    "Sootea", "Lakhimpur", "Naoboicha", "Ranganadi (ST)"
].sort();
